export const ADD_DESIGNATION_REQUEST = "ADD_DESIGNATION_REQUEST";
export const ADD_DESIGNATION_SUCCESS = "ADD_DESIGNATION_SUCCESS";
export const ADD_DESIGNATION_FAIL = "ADD_DESIGNATION_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_MESSAGE="CLEAR_MESSAGE"