export const ADD_SIGNATURE_RECORD_REQUEST = "ADD_SIGNATURE_RECORD_REQUEST";
export const ADD_SIGNATURE_RECORD_SUCCESS = "ADD_SIGNATURE_RECORD_SUCCESS";
export const ADD_SIGNATURE_RECORD_FAIL = "ADD_SIGNATURE_RECORD_FAIL";

export const GET_SIGNATURE_RECORD_REQUEST = "GET_SIGNATURE_RECORD_REQUEST";
export const GET_SIGNATURE_RECORD_SUCCESS = "GET_SIGNATURE_RECORD_SUCCESS";
export const GET_SIGNATURE_RECORD_FAIL = "GET_SIGNATURE_RECORD_FAIL";

export const UPDATE_SIGNATURE_RECORD_STATUS_REQUEST = "UPDATE_SIGNATURE_RECORD_STATUS_REQUEST";
export const UPDATE_SIGNATURE_RECORD_STATUS_SUCCESS = "UPDATE_SIGNATURE_RECORD_STATUS_SUCCESS";
export const UPDATE_SIGNATURE_RECORD_STATUS_FAIL = "UPDATE_SIGNATURE_RECORD_STATUS_FAIL";

export const GET_ACTIVE_ASSISTANT_DIRECTOR_REQUEST = "GET_ACTIVE_ASSISTANT_DIRECTOR_REQUEST";
export const GET_ACTIVE_ASSISTANT_DIRECTOR_SUCCESS = "GET_ACTIVE_ASSISTANT_DIRECTOR_SUCCESS";
export const GET_ACTIVE_ASSISTANT_DIRECTOR_FAIL = "GET_ACTIVE_ASSISTANT_DIRECTOR_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_MESSAGE="CLEAR_MESSAGE";
