export const GET_PRODUCT_COUNT_REQUEST = "GET_PRODUCT_COUNT_REQUEST";
export const GET_PRODUCT_COUNT_SUCCESS = "GET_PRODUCT_COUNT_SUCCESS";
export const GET_PRODUCT_COUNT_FAIL = "GET_PRODUCT_COUNT_FAIL";

export const GET_WAITING_REQUEST_COUNT_REQUEST = "GET_WAITING_REQUEST_COUNT_REQUEST";
export const GET_WAITING_REQUEST_COUNT_SUCCESS = "GET_WAITING_REQUEST_COUNT_SUCCESS";
export const GET_WAITING_REQUEST_COUNT_FAIL = "GET_WAITING_REQUEST_COUNT_FAIL";

export const GET_7DAYS_PRODUCT_REQUEST_REQUEST = "GET_7DAYS_PRODUCT_REQUEST_REQUEST";
export const GET_7DAYS_PRODUCT_REQUEST_SUCCESS = "GET_7DAYS_PRODUCT_REQUEST_SUCCESS";
export const GET_7DAYS_PRODUCT_REQUEST_FAIL = "GET_7DAYS_PRODUCT_REQUEST_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_MESSAGE="CLEAR_MESSAGE"