export const ADD_DEMAND_DATA = "ADD_DEMAND_DATA";
export const DEMAND_DETAIL= "DEMAND_DETAIL";
export const CURRENT_DEMAND= "CURRENT_DEMAND";
export const CLEAR_DEMAND_DATA = "CLEAR_DEMAND_DATA";
export const CLEAR_DETAILS = "CLEAR_DETAILS";
export const UPDATE_DATA = "UPDATE_DATA";


export const GET_ALL_PRODUCT_FROM_LOCATION_REQUEST = "GET_ALL_PRODUCT_FROM_LOCATION_REQUEST";
export const GET_ALL_PRODUCT_FROM_LOCATION_SUCCESS = "GET_ALL_PRODUCT_FROM_LOCATION_SUCCESS";
export const GET_ALL_PRODUCT_FROM_LOCATION_FAIL = "GET_ALL_PRODUCT_FROM_LOCATION_FAIL";

export const GET_ALL_LOCATION_REQUEST = "GET_ALL_LOCATION_REQUEST";
export const GET_ALL_LOCATION_SUCCESS = "GET_ALL_LOCATION_SUCCESS";
export const GET_ALL_LOCATION_FAIL = "GET_ALL_LOCATION_FAIL";

export const SAVE_DEMAND_REQUEST = "SAVE_DEMAND_REQUEST";
export const SAVE_DEMAND_SUCCESS = "SAVE_DEMAND_SUCCESS";
export const SAVE_DEMAND_FAIL = "SAVE_DEMAND_FAIL";


export const GET_ALL_DEMAND_REQUEST = "GET_ALL_DEMAND_REQUEST";
export const GET_ALL_DEMAND_SUCCESS = "GET_ALL_DEMAND_SUCCESS";
export const GET_ALL_DEMAND_FAIL = "GET_ALL_DEMAND_FAIL";


export const POST_DEMAND_QUANTITY_REQUEST = "POST_DEMAND_QUANTITY_REQUEST";
export const POST_DEMAND_QUANTITY_SUCCESS = "POST_DEMAND_QUANTITY_SUCCESS";
export const POST_DEMAND_QUANTITY_FAIL = "POST_DEMAND_QUANTITY_FAIL";


export const UPDATE_DEMAND_STATUS_REQUEST = "UPDATE_DEMAND_STATUS_REQUEST";
export const UPDATE_DEMAND_STATUS_SUCCESS = "UPDATE_DEMAND_STATUS_SUCCESS";
export const UPDATE_DEMAND_STATUS_FAIL = "UPDATE_DEMAND_STATUS_FAIL";


export const GET_ACTIVE_ASSISTANT_DIRECTOR_REQUEST = "GET_ACTIVE_ASSISTANT_DIRECTOR_REQUEST";
export const GET_ACTIVE_ASSISTANT_DIRECTOR_SUCCESS = "GET_ACTIVE_ASSISTANT_DIRECTOR_SUCCESS";
export const GET_ACTIVE_ASSISTANT_DIRECTOR_FAIL = "GET_ACTIVE_ASSISTANT_DIRECTOR_FAIL";

export const GET_DEMAND_BY_ID_REQUEST = "GET_DEMAND_BY_ID_REQUEST";
export const GET_DEMAND_BY_ID_SUCCESS = "GET_DEMAND_BY_ID_SUCCESS";
export const GET_DEMAND_BY_ID_FAIL = "GET_DEMAND_BY_ID_FAIL";

export const ADD_PRODUCT_QUANTITY_THROUGH_DEMAND_REQUEST = "ADD_PRODUCT_QUANTITY_THROUGH_DEMAND_REQUEST";
export const ADD_PRODUCT_QUANTITY_THROUGH_DEMAND_SUCCESS = "ADD_PRODUCT_QUANTITY_THROUGH_DEMAND_SUCCESS";
export const ADD_PRODUCT_QUANTITY_THROUGH_DEMAND_FAIL = "ADD_PRODUCT_QUANTITY_THROUGH_DEMAND_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_MESSAGE="CLEAR_MESSAGE";



