export const GET_ALL_PRODUCT_TYPE_REQUEST = "GET_ALL_PRODUCT_TYPE_REQUEST";
export const GET_ALL_PRODUCT_TYPE_SUCCESS = "GET_ALL_PRODUCT_TYPES_SUCCESS";
export const GET_ALL_PRODUCT_TYPE_FAIL = "GET_ALL_PRODUCT_TYPE_FAIL";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "GADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

export const ADD_PRODUCT_TYPE_REQUEST = "ADD_PRODUCT_TYPE_REQUEST";
export const ADD_PRODUCT_TYPE_SUCCESS = "GADD_PRODUCT_TYPE_SUCCESS";
export const ADD_PRODUCT_TYPE_FAIL = "ADD_PRODUCT_TYPE_FAIL";

export const CLEAR_ERROR="CLEAR_ERROR";
export const CLEAR_MESSAGE="CLEAR_MESSAGE";

